In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('D:\projects\customer churn analysis\datachurn.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\dorea\AppData\Local\Temp\ipykernel_18420\1729216350.py:1: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  df=pd.read_csv('D:\projects\customer churn analysis\datachurn.csv')

In [3]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [4]:
df.head(10)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.4,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.9,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

In [5]:
#for fixing total charges to numeric
df['TotalCharges']=pd.to_numeric(df['TotalCharges'], errors='coerce')

In [6]:
#drop the missing values
df=df.dropna()

In [7]:
#converting churn to binary 
df['Churn']=df['Churn'].map({'Yes':1, 'No':0})

In [8]:
#overall churn rate
df['Churn'].mean()*100

np.float64(26.578498293515356)

In [9]:
#churn By contract
df.groupby('Contract')['Churn'].mean().sort_values(ascending=False)

Contract
Month-to-month    0.427097
One year          0.112772
Two year          0.028487
Name: Churn, dtype: float64

In [10]:
#churn by payment method
df.groupby('PaymentMethod')['Churn'].mean().sort_values(ascending=False)

PaymentMethod
Electronic check             0.452854
Mailed check                 0.192020
Bank transfer (automatic)    0.167315
Credit card (automatic)      0.152531
Name: Churn, dtype: float64

In [11]:
#churn vs tenure
df.groupby('tenure')['Churn'].mean()
#new customers churn more

tenure
1     0.619902
2     0.516807
3     0.470000
4     0.471591
5     0.481203
        ...
68    0.090000
69    0.084211
70    0.092437
71    0.035294
72    0.016575
Name: Churn, Length: 72, dtype: float64

In [ ]:
#churn vs montly charges
df.groupby(pd.cut(df['MonthlyCharges'], bins=5))['Churn'].mean()

MonthlyCharges
(18.15, 38.35]     0.114461
(38.35, 58.45]     0.270189
(58.45, 78.55]     0.295238
(78.55, 98.65]     0.369863
(98.65, 118.75]    0.300573
Name: Churn, dtype: float64

In [17]:
#revenue at risk 
df[df['Churn']==1]['MonthlyCharges'].mean()

np.float64(74.44133226324237)

In [19]:
#creating high risk segments
df.groupby(['Contract','PaymentMethod'])['Churn'].mean().sort_values(ascending=False)
#this gives exact customer groups to target

Contract        PaymentMethod
Month-to-month  Electronic check             0.537297
                Bank transfer (automatic)    0.341256
                Credit card (automatic)      0.327808
                Mailed check                 0.315789
One year        Electronic check             0.184438
                Credit card (automatic)      0.103015
                Bank transfer (automatic)    0.097187
Two year        Electronic check             0.077381
One year        Mailed check                 0.068452
Two year        Bank transfer (automatic)    0.033808
                Credit card (automatic)      0.022414
                Mailed check                 0.008000
Name: Churn, dtype: float64

In [26]:
import pandas as pd

df = pd.read_csv('D:\projects\customer churn analysis\datachurn.csv')

# Clean column names
df.columns = df.columns.str.strip()

# Remove any completely empty columns
df = df.dropna(axis=1, how='all')

# Save clean file
df.to_csv('clean_churn.csv', index=False)

<>:3: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
<>:3: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
C:\Users\dorea\AppData\Local\Temp\ipykernel_18420\1409668525.py:3: SyntaxWarning: "\p" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\p"? A raw string is also an option.
  df = pd.read_csv('D:\projects\customer churn analysis\datachurn.csv')